global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090'] 

- job_name: 'backend'
  metrics_path: /metrics
  static_configs:
  - targets: ['backend:8000']

- job_name: 'node_exporter'
  static_configs:
  - targets: ['node-exporter:9100']
  
- job_name: 'grafana'
  static_configs:
  - targets: ['grafana:3000']

- job_name: 'frontend' 
  metrics_path: /metrics
  static_configs:
  - targets: ['frontend:80']